# Generated by Django 3.2.3 on 2021-06-14 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corevalue',
            old_name='core_value_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='goal_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='skill_category',
            new_name='category',
        ),
    ]
