# Generated by Django 3.2.3 on 2021-06-30 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0004_alter_appraisal_status'),
        ('users', '0008_logs'),
        ('training', '0002_auto_20210614_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentalGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=150)),
                ('due', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appraisals.appraisal')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.goalcategory')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentalCoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=150)),
                ('due', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appraisals.appraisal')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.corevaluecategory')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
