# Generated by Django 3.2.3 on 2021-07-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_auto_20210630_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='employee_rating',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Major Improvement Needed'), (2, '2 - Needs Improvement'), (3, '3 - Meets Expectations'), (4, '4 - Exceeds Expectations'), (5, '5 - Far Exceed Expectations')], null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='manager_rating',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Major Improvement Needed'), (2, '2 - Needs Improvement'), (3, '3 - Meets Expectations'), (4, '4 - Exceeds Expectations'), (5, '5 - Far Exceed Expectations')], null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.IntegerField(blank=True, choices=[(-1, 'REJECTED'), (0, 'PENDINGD'), (1, 'APPROVED')], null=True),
        ),
    ]
