# Generated by Django 3.2.3 on 2021-07-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_auto_20210702_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.IntegerField(blank=True, choices=[(-1, 'REJECTED'), (0, 'PENDINGD'), (1, 'APPROVED')], default=0),
        ),
    ]
