# Generated by Django 3.2.3 on 2021-07-05 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_alter_goal_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='stage3_employee_comment',
            new_name='stage0_employee_comment',
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='stage3_manager_comment',
            new_name='stage0_manager_comment',
        ),
    ]
