#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

postgres_ready() {
  python <<END
import sys
import psycopg2
try:
    psycopg2.connect(
        dbname="${DB_NAME}",
        user="${DB_USER}",
        password="${DB_PASSWORD}",
        host="${DB_HOST}",
        port="${DB_PORT}",
    )
except psycopg2.OperationalError:
    sys.exit(-1)
sys.exit(0)
END
}

# rabbitmq_ready() {
#   python <<END
# import sys
# import pika
# try:
#   parameters = pika.URLParameters("${RABBITMQ_URL}")
#   connection = pika.BlockingConnection(parameters)
#   if connection.is_open:
#     print('OK')
#     connection.close()
#     exit(0)
# except Exception as error:
#     print('Error:', error.__class__.__name__)
#     sys.exit(-1)
# sys.exit(0)
# END
# }
until postgres_ready; do
  echo >&2 'Waiting for PostgreSQL to become available...'
  sleep 1
done

echo >&2 'PostgreSQL is available'

# until rabbitmq_ready; do
#   echo >&2 'Waiting for Rabbitmq  to become available...'
#   sleep 1
# done
exec "$@"
