# Generated by Django 3.2.3 on 2021-05-24 19:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_company_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverAllAppraisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('stage', models.IntegerField(blank=True, choices=[(0, 'STAGE 1 :Goals Setting Stage'), (1, 'STAGE 2 :Mid-Year Review'), (3, 'STAGE 3 :Year-End Review'), (4, 'STAGE 4 :Reports'), (5, 'STAGE 5 :Calibration'), (6, 'STAGE 6 :Completed')], default=0)),
                ('goal_weightage', models.IntegerField(blank=True, default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('core_value_weightage', models.IntegerField(blank=True, default=25, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('skill_weightage', models.IntegerField(blank=True, default=25, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('stage1_start_date', models.DateField(default=django.utils.datetime_safe.date.today)),
                ('stage1_end_date', models.DateField(default=django.utils.datetime_safe.date.today)),
                ('stage2_start_date', models.DateField(default=django.utils.datetime_safe.date.today)),
                ('stage2_end_date', models.DateField(default=django.utils.datetime_safe.date.today)),
                ('stage3_start_date', models.DateField(default=django.utils.datetime_safe.date.today)),
                ('stage3_end_date', models.DateField(default=django.utils.datetime_safe.date.today)),
                ('reports_end_date', models.DateField(default=django.utils.datetime_safe.date.today)),
                ('calibration_end_date', models.DateField(default=django.utils.datetime_safe.date.today)),
                ('company', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.company')),
            ],
        ),
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, choices=[(0, 'STAGE 1: Employee Goal settings stage'), (1, 'STAGE 1: Employee goal submit stage'), (2, 'STAGE 1: Manager Goal apprave stage'), (3, 'STAGE 1: Manager Approved the goal'), (4, 'STAGE 2: Employee mid year review stage'), (5, 'STAGE 2: Employee mid year submit stage'), (6, 'STAGE 2: Manager mid year approve stage'), (7, 'STAGE 2: Manager Approved mid year review'), (4, 'STAGE 3: Employee end year review stage'), (5, 'STAGE 3: Employee end year submit stage'), (6, 'STAGE 3: Manager end year approve stage'), (7, 'STAGE 3: Manager Approved end year review'), (8, 'STAGE 3: hod end year approve stage'), (9, 'STAGE 3: hod approved year approve stage')], default=0)),
                ('stage1_employee_comment', models.TextField(blank=True, null=True)),
                ('stage1_manager_comment', models.TextField(blank=True, null=True)),
                ('stage2_employee_comment', models.TextField(blank=True, null=True)),
                ('stage2_manager_comment', models.TextField(blank=True, null=True)),
                ('stage3_employee_comment', models.TextField(blank=True, null=True)),
                ('stage3_manager_comment', models.TextField(blank=True, null=True)),
                ('stage1_rejection_comment', models.TextField(blank=True, null=True)),
                ('stage2_rejection_comment', models.TextField(blank=True, null=True)),
                ('stage3_rejection_comment', models.TextField(blank=True, null=True)),
                ('other_properties', models.JSONField(blank=True, null=True)),
                ('overall_appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appraisals.overallappraisal')),
            ],
        ),
    ]
