# Generated by Django 3.2.3 on 2021-06-05 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_logs'),
        ('appraisals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
