# Generated by Django 3.2.3 on 2021-06-14 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisals', '0002_appraisal_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'STAGE 1: Employee Goal settings stage'), (1, 'STAGE 1: Employee goal submit stage'), (2, 'STAGE 1: Manager Goal apprave stage'), (3, 'STAGE 1: Manager Approved the goal'), (4, 'STAGE 2: Employee mid year review stage'), (5, 'STAGE 2: Employee mid year submit stage'), (6, 'STAGE 2: Manager mid year approve stage'), (7, 'STAGE 2: Manager Approved mid year review'), (8, 'STAGE 3: Employee end year review stage'), (9, 'STAGE 3: Employee end year submit stage'), (10, 'STAGE 3: Manager end year approve stage'), (11, 'STAGE 3: Manager Approved end year review'), (12, 'STAGE 3: hod end year approve stage'), (13, 'STAGE 3: hod approved year approve stage')], default=0),
        ),
    ]
