# Generated by Django 3.2.3 on 2021-05-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210523_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='setting',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
