# Generated by Django 3.2.3 on 2021-05-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_permission_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='domain',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
