# Generated by Django 3.2.3 on 2021-07-12 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('logs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.logs')),
                ('is_read', models.BooleanField(default=False)),
            ],
            bases=('users.logs',),
        ),
    ]
