# Generated by Django 3.2.3 on 2021-07-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210712_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='description',
        ),
        migrations.AddField(
            model_name='logs',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
