# Generated by Django 3.2.3 on 2021-07-15 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210709_1530'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
