# Generated by Django 3.2.3 on 2021-07-15 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logs',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
    ]
